### ISSUE TITLE
How is it actually used?

### ISSUE THREAD

**Issue by steven4547466** [ag-gipp/node-mathml#11]
I was unable to find any documentation on how to actually use this module. I was wondering if I missed it, or if it just wasn't made. Thanks.

**Comment by physikerwelt** [comment]
Unfortunately, there is no documentation yet. I hope to find time to address this issue in future versions. The tests https://github.com/ag-gipp/node-mathml/tree/master/test/mathml provide some examples of how to use the module.
Sorry!
